export const navs = [
  { id: 1, name: "Home", href: "/", link: "/" },
  { id: 2, name: "Properties", href: "/properties", link: "/properties" },
  { id: 3, name: "Agents", href: "/agents", link: "/agents" },
  { id: 4, name: "About Us", href: "/about-us", link: "/about-us" },
];

export const properties = [
  {
    id: 1,
    name: "Luxury City Apartment",
    pricePerMonth: 2500,
    location: "Downtown, New York",
    bedrooms: 2,
    bathrooms: 2,
    sizeSqFt: 1200,
    slug: "luxury-city-apartment",
  },
  {
    id: 2,
    name: "Cozy Suburban Home",
    pricePerMonth: 1800,
    location: "Brooklyn, New York",
    bedrooms: 3,
    bathrooms: 2,
    sizeSqFt: 1600,
    slug: "cozy-suburban-home",
  },
  {
    id: 3,
    name: "Modern Loft",
    pricePerMonth: 2200,
    location: "Soho, New York",
    bedrooms: 1,
    bathrooms: 1,
    sizeSqFt: 950,
    slug: "modern-loft",
  },
  {
    id: 4,
    name: "Spacious Family House",
    pricePerMonth: 3200,
    location: "Queens, New York",
    bedrooms: 4,
    bathrooms: 3,
    sizeSqFt: 2100,
    slug: "spacious-family-house",
  },
  {
    id: 5,
    name: "Penthouse Suite",
    pricePerMonth: 5000,
    location: "Manhattan, New York",
    bedrooms: 3,
    bathrooms: 3,
    sizeSqFt: 2500,
    slug: "penthouse-suite",
  },
  {
    id: 6,
    name: "Beachside Villa",
    pricePerMonth: 4200,
    location: "Miami Beach, Florida",
    bedrooms: 4,
    bathrooms: 4,
    sizeSqFt: 2800,
    slug: "beachside-villa",
  },
  {
    id: 7,
    name: "Downtown Studio",
    pricePerMonth: 1500,
    location: "Chicago, Illinois",
    bedrooms: 1,
    bathrooms: 1,
    sizeSqFt: 700,
    slug: "downtown-studio",
  },
  {
    id: 8,
    name: "Countryside Cottage",
    pricePerMonth: 1300,
    location: "Nashville, Tennessee",
    bedrooms: 2,
    bathrooms: 1,
    sizeSqFt: 1100,
    slug: "countryside-cottage",
  },
  {
    id: 9,
    name: "Luxury High-Rise Condo",
    pricePerMonth: 3500,
    location: "San Francisco, California",
    bedrooms: 2,
    bathrooms: 2,
    sizeSqFt: 1350,
    slug: "luxury-high-rise-condo",
  },
  {
    id: 10,
    name: "Modern Townhouse",
    pricePerMonth: 2700,
    location: "Austin, Texas",
    bedrooms: 3,
    bathrooms: 2,
    sizeSqFt: 1750,
    slug: "modern-townhouse",
  },
];
